services:
    marttiphpbb.keeppost.listener:
        class: marttiphpbb\keeppost\event\listener
        arguments:
            - '@template'
        tags:
            - { name: event.listener }
          
